# Generated by Django 5.0.6 on 2026-08-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_billreturn_billreturnitem_cashregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='points_earned',
            field=models.IntegerField(default=0, help_text='Loyalty reward points earned on this bill'),
        ),
        migrations.AddField(
            model_name='bill',
            name='points_redeemed',
            field=models.IntegerField(default=0, help_text='Loyalty points redeemed as discount'),
        ),
    ]
