# Generated by Django 5.0.6 on 2026-08-26 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('return', 'Refund / Return'), ('payment', 'Payment / Settlement'), ('cash_register', 'Cash Register'), ('export', 'Data Export')], max_length=20)),
                ('module', models.CharField(choices=[('inventory', 'Inventory'), ('billing', 'Billing & POS'), ('purchases', 'Purchases & Suppliers'), ('udhaar', 'Udhaar Ledger'), ('cash_register', 'Cash Register'), ('accounts', 'Accounts & Staff')], max_length=20)),
                ('object_repr', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.shop')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
