# Generated by Django 5.0.6 on 2026-08-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='upi_id',
            field=models.CharField(blank=True, default='shopkeeper@upi', help_text='UPI ID for on-screen QR Code payments', max_length=100),
        ),
    ]
