# Generated by Django 5.0.6 on 2026-08-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udhaar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='loyalty_points',
            field=models.IntegerField(default=0, help_text='Reward points earned by customer'),
        ),
    ]
